### ISSUE TITLE
Configuration files should not be versioned

### ISSUE THREAD

**Issue by thorgrin** [CESNET/Nemea-Dashboard#6]
The configuration files should not be kept in git, because it complicated deployment and updates. I suggest that only config.json.example and config.js.example files are versioned and the config.json and config.js are added to the .gitignore. This would allow to easily apply modifications to the configuration (e.g. turn on SSL) and still be able to `git pull` without difficulties.

**Comment by petrstehlik** [comment]
Fixed and merged to master
